source "https://rubygems.org"

gem "rails", "4.2.4"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "bootstrap-sass"
gem "kaminari"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "config"
gem "devise"
gem "cancancan"
gem "paranoia", "~> 2.0"
gem "font-awesome-rails"
gem "jquery-turbolinks"
gem "ransack"
gem "select2-rails"
gem "auto_strip_attributes"
gem "attribute_normalizer"
gem "nprogress-rails"
gem "redis"
gem "redis-namespace"
gem "redis-rails"
gem "redis-rack-cache"
gem "sidekiq"
gem "activerecord-import"
gem "friendly_id", "~> 5.1.0"
gem "figaro"
gem "ckeditor"
gem "paperclip"
gem "nested_form"
gem "closure_tree"
gem "jquery-ui-rails"
source "https://rails-assets.org" do
  gem "rails-assets-datetimepicker"
end
gem "carrierwave"
gem "mini_magick"
gem "carrierwave-dropbox"
gem "isotope-rails"

group :development, :test do
  gem "pry"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "faker"
  gem "factory_girl_rails"
  gem "i18n-tasks"
  gem "rspec-rails"
  gem "railroady"
  gem "mysql2", "~> 0.3.18"
end

group :production do
  gem "rails_12factor"
  gem "pg"
end

