# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a10cd9d3c7c304670e50a38445d6e2ed94629bacefe7b8328b2bf11126112f92beec8f697229b5d86044415aadf1e6173c7a1045ad1f84653ca1182bd1842828

test:
  secret_key_base: 0569e0b87d94398a457e60adbfb3c3ede11dd4e874e58b1df47c2b802e2ee720f26d940121424f73ec44ab0edc6ffcc15153dac319df809a3f85e8bbf3aac6fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
