imports:
  file_types:
    csv:
      - ".csv"
      - ".xls"
      - ".xlsx"
    json: ".json"
  primeuser:
    id: id
    uid: uid
    first_name: first_name
    middle_name: middle_name
    last_name: last_name
    birthday: birthday
    program: program
    class_name: class_name
    status: status
    cohort: cohort
  primeclass:
    id: id
    semester: semester
    student_id: student_id
    class_id: class_id
    class_type: class_type
    course_id: course_id
    course_title: course_title
    reg_status: reg_status
  question:
    id: id
    name: name
    question_type: question_type
    priority: priority
  data_types:
    - model: prime_user
      verify_attributes:
        - uid
    - model: prime_class
      verify_attributes:
        - semester
        - student_id
        - class_id
        - course_id
    - model: question
      verify_attributes:
        - question_type
  image_loading_size: "30x30"
data_types_import:
  prime_user: "prime_user"
  prime_class: "prime_class"
  question: "question"
collum_check_import:
  prime_user: "uid"
  prime_class: "semester"
  question: "question_type"
class_room:
  tabs:
    class_rooms: "Class room"
    members: "Member"
  students:
    tabs:
      class_rooms: "Class room"
      members: "Member"
users:
  tabs:
    - activities
    - timeline
    - settings
languages:
  en: "en"
  ja: "ja"
  vi: "vi"
flag_size: "20x15"
